version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Users
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 13306:8080
